<a href="https://colab.research.google.com/github/srv96/AI-ML-TensorFlow/blob/main/RNN_shapes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
# Things to know and memorize

# N = number of samples
# T = sequence length
# D = number of input features
# M = number of hidden units
# K = number of output units

In [37]:
#Make some Data

N = 2
T = 10
D = 3
K = 2
X = np.random.randn(N, T, D)

In [38]:
M = 5
i = tf.keras.layers.Input(shape=(T,D))
x = tf.keras.layers.SimpleRNN(M)(i)
x = tf.keras.layers.Dense(K)(x)

model = tf.keras.models.Model(i,x)

In [39]:
y_hat = model.predict(X)
print(y_hat)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 264ms/step
[[1.7311623 2.0808907]
 [1.5753753 0.9972298]]


In [40]:
model.summary()

Model: "functional_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer_4 (InputLayer)           │ (None, 10, 3)               │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn_4 (SimpleRNN)             │ (None, 5)                   │              45 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 2)                   │              12 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 57 (228.00 B)

 Trainable params: 57 (228.00 B)

 Non-trainable params: 0 (0.00 B)

In [41]:
a, b, c = model.layers[1].get_weights()
print(a.shape , b.shape , c.shape)

(3, 5) (5, 5) (5,)


In [42]:
Wx , Wh, bh = model.layers[1].get_weights()
Wo, bo = model.layers[2].get_weights()

In [43]:
h_last = np.zeros(M)
x = X[0]
Y_hat = []
for t in range(T):
  h = np.tanh(x[t].dot(Wx) + h_last.dot(Wh) + bh)
  y = h.dot(Wo) + bo
  Y_hat.append(y)

  #assign h to h_last
  h_last = h

print(y_hat[-1])

[1.5753753 0.9972298]


In [45]:
#where N > 1
h_last = np.zeros(M)

Y_hat = []
for n in range(N):
  x = X[n]
  for t in range(T):
    h = np.tanh(x[t].dot(Wx) + h_last.dot(Wh) + bh)
    y = h.dot(Wo) + bo
    Y_hat.append(y)
  #assign h to h_last
  h_last = h

print(y_hat[-1])

[1.5753753 0.9972298]


In [46]:
print("X[0][0].shape : ",X[0][0].shape)
print("Wx.shape : ",Wx.shape)
print("X[0][0].dot(Wx).shape : ",X[0][0].dot(Wx).shape)
print("Wo.shape : ",Wo.shape)
print("X[0][0].dot(Wx).dot(Wo).shape : ",X[0][0].dot(Wx).dot(Wo).shape)
print("\n")
print("X[0][0] : ",X[0][0])
print("Wx : ",Wx)
print("X[0][0].dot(Wx) : " ,X[0][0].dot(Wx))
print("Wo : ", Wo)
print("X[0][0].dot(Wx).dot(Wo) : ",X[0][0].dot(Wx).dot(Wo))

X[0][0].shape :  (3,)
Wx.shape :  (3, 5)
X[0][0].dot(Wx).shape :  (5,)
Wo.shape :  (5, 2)
X[0][0].dot(Wx).dot(Wo).shape :  (2,)


X[0][0] :  [ 1.47111845  1.03589582 -0.85895748]
Wx :  [[-0.316365    0.63591033 -0.20549476  0.47945982 -0.6667695 ]
 [-0.6773019  -0.7491985  -0.50180984 -0.55246747  0.43515056]
 [ 0.5266475  -0.24537629  0.18906647  0.76327497  0.44709188]]
X[0][0].dot(Wx) :  [-1.6193924   0.37017563 -0.9845299  -0.52257729 -0.91415918]
Wo :  [[-0.9053306  -0.7498381 ]
 [ 0.81858134  0.7250707 ]
 [-0.6109058  -0.4857667 ]
 [-0.23160887 -0.80302674]
 [ 0.02573258  0.22839808]]
X[0][0].dot(Wx).dot(Wo) :  [2.46806927 2.17178883]
